version: 2.1
jobs:
  build-and-test:
    macos:
      xcode: 11.4.0
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: test
    steps:
      - checkout
      - run: bundle install
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan

  adhoc:
    macos:
      xcode: 11.4.0
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: adhoc
    steps:
      - checkout
      - run: bundle install
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output

  buildanddeploytotestflight:
    macos:
      xcode: 11.4.0
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: buildanddeploytotestflight
    steps:
      - checkout
      - run: bundle install
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output
          
workflows:
  build-test-adhoc-testflight:
    jobs:
      - build-and-test
      - buildanddeploytotestflight:
          filters:
            branches:
              only: develop
          requires:
            - build-and-test            
