version: 2.1
jobs:
  build-and-test:
    macos:
      xcode: 11.4.0
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: test
    steps:
      - checkout
      - run: bundle install
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan

  adhoc:
    macos:
      xcode: 11.4.0
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: adhoc
    steps:
      - checkout
      - run: bundle install
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output

  buildanddeploytotestflight:
    macos:
      xcode: 11.4.0
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: buildanddeploytotestflight
    steps:
      - checkout
      - run: bundle install
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output
          
  update-localizations-test-deploy:
    macos: 
      xcode: 11.4.0
    steps:
      - checkout
      - run: bundle install
      - run:
          name: Fastlane
          command: bundle exec fastlane xliffimport
      - run:
          name: Fastlane
          command: bundle exec fastlane test
      - add_ssh_keys
      - deploy:
          name: Push back to branch
          command: |
            git config credential.helper 'cache --timeout=120'
            git config user.email "localization_bot@willowtreeapps.com"
            git config user.name "Localization Bot"
            git add -A
            git commit --allow-empty -m "Updated localizations [ci skip]"
            git push -q git@github.com:willowtreeapps/vocable-ios.git ${CIRCLE_BRANCH}
    
workflows:
  build-test-adhoc-testflight:
    jobs:
      - build-and-test:
          filters:
            branches:
              ignore: /crowdin.*/ 
      - buildanddeploytotestflight:
          filters:
            branches:
              only: develop
          requires:
            - build-and-test
  localize-build-test:
    jobs:
      - update-localizations-test-deploy:
          filters:
            branches:
              only: /crowdin.*/           